zama-ai/kms

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-core-configmap.yaml
- charts/kms-core/values.yaml
> chore(chart): bump chart to 1.0.2

- .github/PULL_REQUEST_TEMPLATE.md
- .gitignore
- README.md
- SECURITY.md
- charts/kms-core/Chart.yaml
- charts/kms-core/README.md
- charts/kms-core/values.yaml
- docs/README.md
- docs/SUMMARY.md
- docs/developer/contributing.md
- docs/guides/on_prem_installation.md
This PR updates a few old references that pointed to the internal repo to point to the public one
> chore: update references to public repo

- core/service/src/client/js_api.rs
- core/service/src/client/mod.rs
- core/service/src/engine/threshold/service/user_decryptor.rs
- core/threshold/src/execution/endpoints/decryption_non_wasm.rs
Closes https://github.com/zama-ai/kms-internal/issues/2684
> chore: fix user dec docs; remove useless SessionParameter

- core/grpc/src/rpc_types.rs
- core/service/src/client/mod.rs
Closes https://github.com/zama-ai/kms-internal/issues/2562
Closes https://github.com/zama-ai/kms-internal/issues/2255
> chore: correctly using packing in user decrypt

- Cargo.lock
- core/service/config/compose_1.toml
- core/service/config/compose_2.toml
- core/service/config/compose_3.toml
- core/service/config/compose_4.toml
- core/service/config/compose_centralized.toml
- core/service/config/default_1.toml
- core/service/config/default_2.toml
- core/service/config/default_3.toml
- core/service/config/default_4.toml
- core/service/config/default_centralized.toml
- core/service/config/default_centralized_enclave.toml
- observability/Cargo.toml
- observability/src/conf.rs
- observability/src/lib.rs
- observability/src/metrics.rs
- observability/src/sys_metrics.rs
- observability/src/telemetry.rs
Closes [#2634](https://github.com/zama-ai/kms-internal/issues/2634) 
New configuration (with default):
```toml
[telemetry]
tracing_service_name = "kms-threshold-2"
metrics_bind_address = "0.0.0.0:9646"
enable_sys_metrics = true (NEW!!)
refresh_interval_ms = 5000 (NEW!!)
```
Where:
- `enable_sys_metrics`: enables or not the system metrics export (CPU/RAM/network)
- `refresh_interval_ms`: time (in ms) to wait between we measure and export the system metrics
> feat: Add system metric for enclaves

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-gen-keys-job.yaml
- charts/kms-core/templates/kms-threshold-init-job.yaml
- charts/kms-core/values.yaml
* Add configurable kms-init timeout
* Add resources block for gen-keys job
> Helm chart kms init and gen-key jobs improvements

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-core-statefulset.yaml
Fix: conditionally set environment variables for deployment that use awskms
> Fix(chart) kms env variables for non awskms deployment

- Cargo.toml
> build: remove unneeded dependency

- ci/slab.toml
- core/service/src/vault/keychain/awskms.rs
In the end decided to return error as the callers are also logging it
> chore: fix error logging in vault

- core/service/src/engine/threshold/service/crs_generator.rs
Closes https://github.com/zama-ai/kms-internal/issues/2691
> chore: CRS ceremony use base session (no PRSS needed).

- core/service/src/engine/threshold/service/preprocessor.rs
Closes https://github.com/zama-ai/kms-internal/issues/2713
> fix: store an error in metada instead of deleting entry after preproc cancel

- core/service/src/cryptography/signcryption.rs
> chore: Add check to make sure we error out instead of panic in case of underflow

- core/service/src/cryptography/backup_pke.rs
> chore: handle error instead of unwrap

- core/threshold/src/malicious_execution/mod.rs
> chore: gating malicious producer trait behind degree 4

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-gen-keys-configmap.yaml
> fix(chart): fix write keys

- core/service/src/engine/threshold/service/crs_generator.rs
- core/service/src/engine/threshold/service/public_decryptor.rs
- core/service/src/engine/threshold/service/user_decryptor.rs
> fix: remove error increment counted twice

- .github/workflows/global-common-workflow.yml
- Cargo.lock
- Cargo.toml
Fix https://rustsec.org/advisories/RUSTSEC-2025-0055
> chore: update tracing-subscriber

- .github/workflows/check-rust-stable-version.yml
- .github/workflows/ci_lint.yml
- .github/workflows/codeql.yml
- .github/workflows/common-docker-big-instance.yml
- .github/workflows/common-nitro-enclave.yml
- .github/workflows/common-release-workspace-cargo.yml
- .github/workflows/common-testing-big-instance.yml
- .github/workflows/common-testing.yml
- .github/workflows/common-update-argocd.yml
- .github/workflows/dependencies_analysis.yml
- .github/workflows/global-common-workflow.yml
- .github/workflows/helm-lint.yml
- .github/workflows/helm-release.yml
- .github/workflows/helm-test.yml
- .github/workflows/npm-release.yml
- .github/workflows/on-release-images.yml
- .github/workflows/release.yml
- .github/workflows/sync-on-push.yml
- .github/workflows/workflow-pr-dockerfile.yml
- .github/workflows/workflow-pr-test-enclave.yml
Apply naming convention for ci workflows
> fix(ci): Add convention to ci workflow

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-core-configmap.yaml
Change tracing configuration in helm-chart to allow exposing metrics without trace forwarding
See https://github.com/zama-ai/kms-internal/issues/2710
> feat(charts): allow enabling metrics without enabling traces forwarding

- .github/workflows/common-testing-big-instance.yml
- .github/workflows/common-testing.yml
- .github/workflows/main.yml
> fix(kms-core): fix nextest test thread

- .github/workflows/common-testing.yml
> fix(kms-core): fix nextest for main

- .github/workflows/sync-on-push.yml
Add lfs boolean to checkout action
5. Missing CI?
> fix(kms-core): add lfs bool for checkout

- .github/workflows/sync-on-push.yml
> fix: fix sync tags

- Cargo.lock
- Cargo.toml
- bc2wrap/Cargo.toml
- core-client/Cargo.toml
- core-client/src/lib.rs
- core-client/tests-utils/Cargo.toml
- core/grpc/Cargo.toml
- core/service/Cargo.toml
- core/service/src/vault/storage/s3.rs
- core/service/tests-utils/Cargo.toml
- core/service/tests/integration_test.rs
- core/threshold/Cargo.toml
- core/threshold/src/execution/keyset_config.rs
- core/threshold/src/networking/sending_service.rs
- observability/Cargo.toml
- tools/kms-health-check/Cargo.toml
This PR enhances the maintainability and security posture of the KMS project by reorganizing and documenting all dependencies across the workspace.
- Reordered all dependencies alphabetically in every `Cargo.toml` file across the workspace
- Consistent structure: Internal Zama modules first, then external dependencies in alphabetical order
- Added detailed inline documentation for all dependencies in the root `Cargo.toml`:
- Purpose description: What each dependency does
- Risk assessment: LOW/MEDIUM/HIGH RISK classification
- Maintainer info: Who maintains the package (e.g., RustCrypto org, tokio team)
- Popularity metrics: Download counts as trust indicators
- Security notes: Special considerations for crypto/security-critical dependencies
- Deprecation warnings: Flagged deprecated …
> chore: deps risks assesment, reordering and annotation

- .github/workflows/common-testing-big-instance.yml
- .github/workflows/npm-release.yml
Fix the permission error happened here https://github.com/zama-ai/kms/actions/runs/17863017203
5. Missing CI?
> fix: fx npm release permission

- .github/workflows/test-reporter.yml
> fix: fix test reporter exit

- .github/workflows/workflow-pr-test-enclave.yml
> fix(ci): fix wf for enclave

- core/service/src/engine/threshold/service/public_decryptor.rs
- core/service/src/engine/threshold/service/user_decryptor.rs
This PR is the attempt to fix performance degradation we see since e70bf10.
It removes an explicit check for an existing key that would lock and thus block concurrent requests, and replaces it with a cheaper check in the cache (that we had in the code-base already, just at a later point in the function).
> fix: remove locking fhe key check and replace with cache refresh

- core/grpc/build.rs
- core/grpc/proto/kms.v1.proto
- core/grpc/src/rpc_types.rs
- core/service/src/client/key_gen.rs
- core/service/src/engine/centralized/central_kms.rs
- core/service/src/engine/centralized/service/key_gen.rs
- core/service/src/engine/centralized/service/preprocessing.rs
- core/service/src/engine/threshold/service/key_generator.rs
Changes the protofile (**BREAKING**) in the KeyGen response such that the digests are given in a Vec (to fix the order).
Also properly implement the centralized preproc logic, such that we fetch the parameters from the preproc call.
Related issue in tech-spec
https://github.com/zama-ai/tech-spec/issues/314
5. Missing CI?
More details and explanations for the checklist and dependency updates can be found in …
> fix!: digest order and centralized preproc

- charts/kms-core/Chart.yaml
- charts/kms-core/templates/kms-core-client-configmap.yaml
- charts/kms-core/templates/kms-gen-keys-configmap.yaml
Fix core-client configmap with port client
5. Missing CI?
> fix(ci): fix core-client configmap with port client
